replicaCount: 3

image:
  repository: ghcr.io/horizon-school-of-digital-technologies/simple-webapp-color
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hostname: 'mohamedhedibenjdida.color.horizon-workspaces.com'

persistence:
  enabled: true
  size: 1Gi
  storageClass: gp2
  accessMode: ReadWriteOnce
  mountPath: '/tmp/data'
